import Head from 'next/head'
import { getFeaturedEvents } from '../dummy-data'

export default function Home() {
  const featuredEvents = getFeaturedEvents()
  return (
    <div className=''>
      <Head>
        <title>Next Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      
    </div>
  )
}
